### PR TITLE
Add Nightly builds

### PR DESCRIPTION
**Pull request by bladeoner**
This PR will make Nightly builds available for download.

When you click on "libogc build - passing", click on the latest workflow run name, the artifacts will be available for download.

### CODE REVIEW

**Comment by Extrems** [comment]
This is copying the wrong include directory and is missing `gamecube_rules` and `wii_rules`.

**Comment by bladeoner** [comment]
Which include directory should be copied?

**Comment by bladeoner** [comment]
Where should it be located?

After the compile is completed I only see these folders:

image

**Comment by Extrems** [comment]
You need to `make install-headers`, which is implied by `make install`. You probably shouldn't be shortcircuiting the makefile.

**Comment by bladeoner** [comment]
Thanks for the pointers, we will get there. It seems I've got it I will update the PR.

**Comment by bladeoner** [comment]
The PR has been updated and rebased.

**Comment by Extrems** [comment]
You can set the DESTDIR variable to install somewhere else.

**Comment by bladeoner** [comment]
It will upload the original destination directory, this will save some lines.

**Pull request merged**
